apiVersion: v1
kind: Service
metadata:
  name: {{ include "redoc.fullname" . }}
  labels:
    {{- include "redoc.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "redoc.name" . }}
    helm.sh/chart: {{ include "redoc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.env.PORT }}
  selector:
    {{- include "redoc.selectorLabels" . | nindent 4 }}
